[package]
name = "candle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candle-core = "0.4.1"
candle-nn = "0.4.1"
half = "2"
magnus = "0.6"

[profile.test]
opt-level = 3