name: build
on: pull_request
jobs:
  build:
    runs-on: red-candle-runner
    steps:
      - uses: actions/checkout@v3
      
      # Cache Rust dependencies
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            tmp
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Cache HuggingFace models
      - name: Cache HuggingFace models
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/huggingface
            ~/Library/Caches/huggingface
          key: ${{ runner.os }}-huggingface-models-v1-${{ hashFiles('test/model_manifest.txt') }}
          restore-keys: |
            ${{ runner.os }}-huggingface-models-v1-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Display Memory Usage
        run: free -h

      - name: Display Disk Space Before Test
        run: df -h

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      # Compile the native extension first
      - name: Compile native extension
        run: bundle exec rake compile

      # Pre-download models if not cached
      - name: Pre-download test models
        run: |
          echo "Pre-downloading models to avoid rate limits..."
          # Try the main download script first (requires compiled extension)
          if bundle exec ruby script/download_test_models.rb; then
            echo "Models downloaded successfully with Candle"
          else
            echo "Falling back to HTTP downloader..."
            ruby script/download_models_http.rb
          fi
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_HOME: ~/.cache/huggingface

      - name: Run tests with Valgrind Massif (Peak Memory)
        run: valgrind --tool=massif --massif-out-file=massif.out bundle exec rake test
        env:
          HF_HOME: ~/.cache/huggingface
          HF_OFFLINE: true  # Use only cached models

      - name: Display Peak Memory Usage
        run: |
          ms_print massif.out | head -n 30

      - name: Display Disk Space After Test
        run: df -h

      - run: bundle exec yard --fail-on-warning --readme README.md --markup markdown --markup-provider redcarpet